name: Alpine Regression Tests

# disable automatic testing for Alpine until we decide what goes in alpine vs. alpine-full
# on: [push, workflow_dispatch]
on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build the Docker image
      run: docker build . --file alpine/Dockerfile --tag dalibo/pandocker:xxxxx-test-githubci-xxxxx

    - name: Regression Tests
      run: TAG=xxxxx-test-githubci-xxxxx VARIANT=alpine ./tests/libs/bats-core/bin/bats tests/extra.bats --tap
